name: build and checks
on:
    push:
        branches: main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Setup Go
              uses: actions/setup-go@v2
              with:
                go-version: '1.24.2'
            - name: Checkout sources
              uses: actions/checkout@v4.1.5
            - name: Run Build
              run: ./build.sh